export const SET_APPLIANCES = "SET_APPLIANCES";
export const FETCH_APPLIANCES_FAILED = "FETCH_APPLIANCES_FAILED";

export const SET_SINGLE_APPLIANCE = "SET_SINGLE_APPLIANCE";
export const FAILED_SINGLE_APPLIANCE = "SET_SINGLE_FAILED";
