export const SET_APPLIANCES = "SET_APPLIANCES";
export const FETCH_APPLIANCES_FAILED = "FETCH_APPLIANCES_FAILED";

export const SET_SINGLE_APPLIANCE = "SET_SINGLE_APPLIANCE";
export const FAILED_SINGLE_APPLIANCE = "SET_SINGLE_FAILED";

export const SEND_COMMENT_SUCCESS = "SEND_COMMENT_SUCCESS";

export const SEND_COMMENT_FAILED = "SEND_COMMENT_FAILED";

export const FETCH_REVIEW_SUCCESS = "FETCH_REVIEW_SUCCESS";

export const FETCH_REVIEW_FAILED = "FETCH_REVIEW_FAILED";

export const AUTH_START = "AUTH_START";

export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const AUTH_FAIL = "AUTH_FAIL";
